{{ if eq .chezmoi.os "android" }}
[".local/lib/pipx.pyz"]
    type = "file"
	executable = true
    url = "https://github.com/pypa/pipx/releases/latest/download/pipx.pyz"
	refreshPeriod = "168h"
{{ end }}
